import PDFDocument from 'pdfkit';
import { IReportExporter, ExportData, ExportOptions } from './exporter.interface';

export class PDFExporter implements IReportExporter {
  async export(data: ExportData, options: ExportOptions): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const chunks: Buffer[] = [];

      const doc = new PDFDocument({
        size: 'A4',
        layout: 'landscape',
        margin: 40,
        bufferPages: true,
      });

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      // Title
      doc.fontSize(18).font('Helvetica-Bold').text(data.title, { align: 'center' });
      doc.moveDown(0.5);

      // Metadata
      doc.fontSize(9).font('Helvetica')
        .text(`Report ID: ${data.metadata.reportId}`, { align: 'left' })
        .text(`Generated at: ${data.metadata.generatedAt}`, { align: 'left' })
        .text(`Generated by: ${data.metadata.generatedBy}`, { align: 'left' });
      doc.moveDown(1);

      // Table
      const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
      const colWidth = Math.min(pageWidth / data.columns.length, 150);
      const tableLeft = doc.page.margins.left;

      // Table header
      const headerY = doc.y;
      doc.fontSize(8).font('Helvetica-Bold');
      data.columns.forEach((col, idx) => {
        doc.text(col.label, tableLeft + idx * colWidth, headerY, {
          width: colWidth - 4,
          align: 'left',
          lineBreak: false,
        });
      });

      doc.moveTo(tableLeft, headerY + 14)
        .lineTo(tableLeft + data.columns.length * colWidth, headerY + 14)
        .stroke();

      doc.y = headerY + 18;

      // Table rows
      doc.font('Helvetica').fontSize(7);
      for (const row of data.rows) {
        const rowY = doc.y;

        // Check if we need a new page
        if (rowY + 14 > doc.page.height - doc.page.margins.bottom) {
          doc.addPage();
          doc.y = doc.page.margins.top;
        }

        const currentY = doc.y;
        data.columns.forEach((col, idx) => {
          const val = String(row[col.key] ?? '');
          doc.text(val, tableLeft + idx * colWidth, currentY, {
            width: colWidth - 4,
            align: 'left',
            lineBreak: false,
          });
        });
        doc.y = currentY + 13;
      }

      // Draw diagonal watermark on every page
      const pages = doc.bufferedPageRange();
      for (let i = pages.start; i < pages.start + pages.count; i++) {
        doc.switchToPage(i);
        doc.save();
        doc.opacity(0.08);
        doc.fontSize(48).font('Helvetica-Bold');
        doc.translate(doc.page.width / 2, doc.page.height / 2);
        doc.rotate(-45, { origin: [0, 0] });
        doc.text(options.watermarkText, -200, -20, {
          width: 400,
          align: 'center',
        });
        doc.restore();
      }

      doc.end();
    });
  }
}
