export const ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  LEASING_OPS_MANAGER: 'LEASING_OPS_MANAGER',
  TEST_PROCTOR: 'TEST_PROCTOR',
  ANALYST: 'ANALYST',
  STANDARD_USER: 'STANDARD_USER',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const ALL_ROLES = Object.values(ROLES) as RoleName[];

export const PERMISSIONS = {
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DEACTIVATE: 'user:deactivate',
  USER_ASSIGN_ROLE: 'user:assign_role',

  PROPERTY_CREATE: 'property:create',
  PROPERTY_READ: 'property:read',
  PROPERTY_UPDATE: 'property:update',

  LISTING_CREATE: 'listing:create',
  LISTING_READ: 'listing:read',
  LISTING_UPDATE: 'listing:update',

  METRIC_DEFINITION_CREATE: 'metric_definition:create',
  METRIC_DEFINITION_READ: 'metric_definition:read',
  METRIC_DEFINITION_UPDATE: 'metric_definition:update',
  METRIC_CALC_TRIGGER: 'metric_calc:trigger',
  METRIC_CALC_READ: 'metric_calc:read',

  TEST_SITE_CREATE: 'test_site:create',
  TEST_SITE_READ: 'test_site:read',
  TEST_SITE_UPDATE: 'test_site:update',

  TEST_SESSION_CREATE: 'test_session:create',
  TEST_SESSION_READ: 'test_session:read',
  TEST_SESSION_UPDATE: 'test_session:update',
  TEST_SESSION_CANCEL: 'test_session:cancel',

  SEAT_ALLOCATION_CREATE: 'seat_allocation:create',
  SEAT_ALLOCATION_READ: 'seat_allocation:read',
  SEAT_ALLOCATION_UPDATE: 'seat_allocation:update',

  REPORT_CREATE: 'report:create',
  REPORT_READ: 'report:read',
  REPORT_SHARE: 'report:share',
  REPORT_EXPORT: 'report:export',

  NOTIFICATION_READ: 'notification:read',
  NOTIFICATION_MANAGE_TEMPLATES: 'notification:manage_templates',

  MESSAGE_READ: 'message:read',
  MESSAGE_VIEW_FAILURES: 'message:view_failures',

  BLACKLIST_CREATE: 'blacklist:create',
  BLACKLIST_READ: 'blacklist:read',
  BLACKLIST_DELETE: 'blacklist:delete',

  AUDIT_LOG_READ: 'audit_log:read',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<RoleName, PermissionKey[]> = {
  SYSTEM_ADMIN: Object.values(PERMISSIONS) as PermissionKey[],

  LEASING_OPS_MANAGER: [
    PERMISSIONS.PROPERTY_CREATE,
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.PROPERTY_UPDATE,
    PERMISSIONS.LISTING_CREATE,
    PERMISSIONS.LISTING_READ,
    PERMISSIONS.LISTING_UPDATE,
    PERMISSIONS.METRIC_DEFINITION_CREATE,
    PERMISSIONS.METRIC_DEFINITION_READ,
    PERMISSIONS.METRIC_DEFINITION_UPDATE,
    PERMISSIONS.METRIC_CALC_TRIGGER,
    PERMISSIONS.METRIC_CALC_READ,
    PERMISSIONS.REPORT_CREATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_SHARE,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.NOTIFICATION_READ,
  ],

  TEST_PROCTOR: [
    PERMISSIONS.TEST_SITE_CREATE,
    PERMISSIONS.TEST_SITE_READ,
    PERMISSIONS.TEST_SITE_UPDATE,
    PERMISSIONS.TEST_SESSION_CREATE,
    PERMISSIONS.TEST_SESSION_READ,
    PERMISSIONS.TEST_SESSION_UPDATE,
    PERMISSIONS.TEST_SESSION_CANCEL,
    PERMISSIONS.SEAT_ALLOCATION_CREATE,
    PERMISSIONS.SEAT_ALLOCATION_READ,
    PERMISSIONS.SEAT_ALLOCATION_UPDATE,
    PERMISSIONS.NOTIFICATION_READ,
  ],

  ANALYST: [
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.LISTING_READ,
    PERMISSIONS.METRIC_DEFINITION_READ,
    PERMISSIONS.METRIC_CALC_TRIGGER,
    PERMISSIONS.METRIC_CALC_READ,
    PERMISSIONS.REPORT_CREATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.NOTIFICATION_READ,
  ],

  STANDARD_USER: [
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.LISTING_CREATE,
    PERMISSIONS.LISTING_READ,
    PERMISSIONS.LISTING_UPDATE,
    PERMISSIONS.TEST_SESSION_READ,
    PERMISSIONS.SEAT_ALLOCATION_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
};
